name: motaperp_seat_application
description: A new Flutter project.


publish_to:

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  fluttertoast:
  mask_text_input_formatter:
  shared_preferences:
  http:
  focused_menu:
  path_provider:
  flutter_launcher_icons:
  flutter_bloc:
  change_app_package_name:
  barcode_scan2:
  intl:
  dropdown_search: 3.0.1
  flutter_datetime_picker:
  turkish:
  cupertino_icons:
  provider:
  connectivity_plus:



flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/motap.jpeg"

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/icons/motap.png
    - assets/icons/motap.jpeg
    - assets/icons/task_order_icons/scan.png
    - assets/icons/task_order_icons/cakim.png
    - assets/icons/task_order_icons/dikim.png
    - assets/icons/task_order_icons/kesim.png
    - assets/icons/task_order_icons/sevk.png
    - assets/icons/task_order_icons/kalitekontrol.png
    - assets/icons/task_order_icons/paket.png
    - assets/icons/task_order_icons/depo.png
    - assets/icons/report_icons/bakiye.png
    - assets/icons/report_icons/planlama.png
    - assets/icons/report_icons/cari.png
    - assets/icons/report_icons/ayrintilihesap.png
    - assets/icons/report_icons/siparisozet.png
    - assets/icons/report_icons/hakedis.png
    - assets/icons/report_icons/isemriistatistik.png
    - assets/icons/report_icons/kasahareketi.png
    - assets/icons/task_order_icons/paketleme.png
    - assets/icons/task_order_icons/sevk.png
    - assets/icons/report_icons/cek.png
    - assets/icons/report_icons/senet.png
    - assets/icons/report_icons/personeller.png

